module.exports = {
  numberOfStartingIngredients: 10,
  numberOfStartingSteps: 6,
  numberOfStartingNotes: 2,
  recipes: {
    courseTypes: [
      'appetizer',
      'beverage',
      'breakfast',
      'brunch',
      'dessert',
      'dinner',
      'lunch',
      'side'
    ],
    dishTypes: [
      'appetizer-snack',
      'bread',
      'brownie',
      'cake',
      'candy-fudge',
      'casserol-gratin',
      'cobbler-crumble',
      'cocktail',
      'dressing-sauce-spread',
      'frozen-dessert',
      'main',
      'martini',
      'pasta-salad',
      'pasta',
      'pastry',
      'pie',
      'pizza',
      'salad',
      'sandwich',
      'smoothie',
      'soup-stew-chili',
      'stir-fry',
      'wrap'
    ],
    cuisines: [
      'african',
      'american',
      'asian',
      'cajun-creole',
      'californian',
      'caribbean',
      'central-south-american',
      'chinese',
      'cuban',
      'eastern-european',
      'english',
      'french',
      'german',
      'indian',
      'irish',
      'italian',
      'japanese',
      'korean',
      'latin-american',
      'mediterranean',
      'mexican',
      'middle-astern',
      'scandinavian',
      'southern',
      'spanish-portuguese',
      'thai',
      'turkish',
      'vietnamese',
      'not-specified'
    ],
    dietaryRestrictions: [
      'gluten-free',
      'healthy',
      'high-fiber',
      'kid-friendly',
      'low-fat',
      'low-sodium',
      'low-no-sugar',
      'organic',
      'raw',
      'vegan',
      'vegetarian',
      'none'
    ]
  },
  specialCharacters: [
    '°',
    '¼',
    '½',
    '¾',
    '⅓',
    '⅔',
    '⅕',
    '⅖',
    '⅗',
    '⅘',
    '⅙',
    '⅚',
    '⅛',
    '⅜',
    '⅝',
    '⅞',
    '⅐',
    '⅑',
    '⅒'
  ]
}
